### ISSUE TITLE
Error on Docker Container Startup with USB JMicron Adapter: Two Devices Connected

### ISSUE THREAD

**Issue by Eliastik** [prometheus-community/smartctl_exporter#181]
### Description

I encountered an error during the startup of the Docker container, with a USB JMicron adapter (an USB enclosure with two HDD). The error messages are:

`Smartctl open device: /dev/sda [USB JMicron] failed: Two devices connected, try '-d usbjmicron,[01]'`

And:

`Smartctl open device: /dev/sdb [USB JMicron] failed: Two devices connected, try '-d usbjmicron,[01]'`

I also have this error message:

`Device open failed, device did not return an IDENTIFY DEVICE structure, or device is in a low-power mode" device=/dev/sda`

Same for sdb

### Steps to Reproduce

1. Start a Docker container with the image, example docker-compose.yml config:
```
version: "3"
services:
  smart-exporter:
    image: prometheuscommunity/smartctl-exporter:v0.11.0
    container_name: smart-exporter
    hostname: smart-exporter
    restart: unless-stopped
    privileged: true
    user: root
```
3. Have an USB enclosure with two HDD connected, and connect it to the server/computer
4. Observe the error during the startup of the Docker container.

### Expected Behavior

Expected the Docker container to start successfully and the `smartctl` command to work without errors when a USB enclosure with two hard drives is connected.

### Actual Behavior

Encountered the error message mentioned above during the startup of the Docker container.

### Additional Information

- Operating System: Host - Ubuntu 20.04.6 LTS
- Docker Image: v0.11.0
