### ISSUE TITLE
/metrics shows error :  was collected before with the same name and label values

### ISSUE THREAD

**Issue by ChaoHsupin** [prometheus-community/smartctl_exporter#58]
Hello, thank you for your work. I met a problem , `/metrics` shows:
````
An error has occurred while serving metrics:

collected metric "smartctl_device_statistics" { label:<name:"device" value:"/dev/sdb" > label:<name:"model_family" value:"" > label:<name:"model_name" value:"ST4000NM000A-2HZ100" > label:<name:"serial_number" value:"WJG0S0A0" > label:<name:"statistic_flags_long" value:"valid" > label:<name:"statistic_flags_short" value:"V---" > label:<name:"statistic_name" value:"Vendor Specific" > label:<name:"statistic_table" value:"Vendor Specific Statistics" > gauge:<value:0 > } was collected before with the same name and label values
````

- exporter in version v0.7.0
smartctl config:
````
smartctl_exporter:
  bind_to: "0.0.0.0:9633"
  url_path: "/metrics"
  fake_json: no
  smartctl_location: /usr/sbin/smartctl
  collect_not_more_than_period: 120s
  devices:
  - /dev/sda
  - /dev/sdb
````

disk mount info:
````
[env]$ df -h
Filesystem                         Size  Used Avail Use% Mounted on
devtmpfs                           126G     0  126G   0% /dev
tmpfs                              126G   12K  126G   1% /dev/shm
tmpfs                              126G  4.1G  122G   4% /run
tmpfs                              126G     0  126G   0% /sys/fs/cgroup
/dev/sda3                          100G   64G   36G  64% /
/dev/sdc1                          3.7T  874G  2.8T  24% /data-hdd1
/dev/sdb1                          3.7T  847G  2.9T  23% /data-hdd0
````
